In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
data = pd.read_csv("zomato.csv")

In [4]:
data.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [5]:
data.head(10)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
5,https://www.zomato.com/bangalore/timepass-dinn...,"37, 5-1, 4th Floor, Bosco Court, Gandhi Bazaar...",Timepass Dinner,Yes,No,3.8/5,286,+91 9980040002\r\n+91 9980063005,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari
6,https://www.zomato.com/bangalore/rosewood-inte...,"19/1, New Timberyard Layout, Beside Satellite ...",Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,8,+91 9731716688\r\n080 26740366,Mysore Road,Casual Dining,NaN,"North Indian, South Indian, Andhra, Chinese",800,"[('Rated 5.0', 'RATED\n Awesome food ??Great ...",[],Buffet,Banashankari
7,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,Yes,Yes,4.6/5,2556,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,"[('Rated 5.0', 'RATED\n I personally really l...",[],Cafes,Banashankari
8,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
9,https://www.zomato.com/bangalore/smacznego-ban...,"2470, 21 Main Road, 25th Cross, Banashankari, ...",Smacznego,Yes,No,4.2/5,504,+91 9945230807\r\n+91 9743804471,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari

In [6]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [8]:
data.shape

(51717, 17)

# Deleting redundant columns

In [9]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [10]:
# List of columns that are required for analysis and will be retained in the dataset
columns_to_keep = [
    'name',
    'online_order',
    'book_table',
    'rate',
    'dish_liked',
    'approx_cost(for two people)'
]

# List of columns that are not relevant for the current analysis and will be removed
# Dropping these columns helps reduce noise and optimize the dataset
columns_to_drop = [
    'url',
    'address',
    'votes',
    'phone',
    'location',
    'rest_type',
    'cuisines',
    'reviews_list',
    'menu_item',
    'listed_in(type)',
    'listed_in(city)'
]

In [11]:
len(columns_to_keep)

6

In [12]:
len(columns_to_drop)

11

In [14]:
# Check the data type of the 'name' column
# This helps verify whether the column is stored as a Pandas Series
type(data["name"])

pandas.core.series.Series

In [20]:
# Create a new DataFrame by selecting only the required columns
# This helps focus the analysis on relevant data and removes unnecessary fields
modify_data = data[columns_to_keep]

In [21]:
modify_data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [24]:
# Drop unnecessary columns from the DataFrame to reduce dataset size
# inplace=True modifies the original DataFrame without creating a copy
data.drop(columns=columns_to_drop, inplace=True)

KeyError: "['url', 'address', 'votes', 'phone', 'location', 'rest_type', 'cuisines', 'reviews_list', 'menu_item', 'listed_in(type)', 'listed_in(city)'] not found in axis"

In [25]:
data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

# Renaming the columns

In [26]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='object')

In [28]:
# Loop through each column name in the DataFrame
# Capitalize the first letter of each column name and print it
# Useful for quickly reviewing column names in a more readable format
for i in data.columns:
    print(i.capitalize())

Name
Online_order
Book_table
Rate
Dish_liked
Approx_cost(for two people)

In [33]:
# Create an empty list to store updated column names
new_column_names = []

# Loop through existing column names in the DataFrame
# Capitalize the first letter of each column name
# Store the transformed column names in a new list
for i in data.columns:
    new_column_names.append(i.capitalize())

In [34]:
new_column_names

['Name',
 'Online_order',
 'Book_table',
 'Rate',
 'Dish_liked',
 'Approx_cost(for two people)']

In [35]:
# Assign the new list of column names to the DataFrame
# This updates the DataFrame with standardized, capitalized column names
data.columns = new_column_names

In [36]:
data.columns

Index(['Name', 'Online_order', 'Book_table', 'Rate', 'Dish_liked',
       'Approx_cost(for two people)'],
      dtype='object')

# Dropping duplicates

In [37]:
# Check the total number of duplicate rows in the DataFrame
# Helps identify redundant records that may affect data quality
data.duplicated().sum()

np.int64(32808)

In [38]:
# Count how many rows are duplicated and how many are unique
# Useful for understanding the overall duplicate distribution in the dataset
data.duplicated().value_counts()

True     32808
False    18909
Name: count, dtype: int64

In [39]:
data.duplicated().head(15)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
dtype: bool

In [40]:
data.duplicated().tail(15)

51702     True
51703     True
51704     True
51705     True
51706     True
51707     True
51708     True
51709     True
51710     True
51711     True
51712     True
51713     True
51714    False
51715     True
51716     True
dtype: bool

In [41]:
# Remove duplicate rows from the DataFrame
# inplace=True ensures duplicates are dropped directly from the original dataset
data.drop_duplicates(inplace=True)

In [42]:
# Recheck the number of duplicate rows after removal
# Confirms that duplicate records have been successfully dropped
data.duplicated().sum()

np.int64(0)

# Remove the NaN values from the dataset

In [43]:
# Calculate the total number of missing (NaN) values in each column
# Helps identify columns that require missing value handling
data.isna().sum()

Name                               0
Online_order                       0
Book_table                         0
Rate                            2418
Dish_liked                     10587
Approx_cost(for two people)      140
dtype: int64

In [44]:
# Remove rows containing any missing (NaN) values
# inplace=True updates the DataFrame directly without creating a new copy
data.dropna(inplace=True)

In [45]:
data.isna().sum()

Name                           0
Online_order                   0
Book_table                     0
Rate                           0
Dish_liked                     0
Approx_cost(for two people)    0
dtype: int64

In [46]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51611,Chung Wah,No,No,2.5 /5,Manchow Soup,800
51617,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
51620,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [48]:
# Reset the DataFrame index after row deletions
# This creates a new default integer index
data.reset_index(inplace = True)

In [49]:
data

,index,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
8245,51611,Chung Wah,No,No,2.5 /5,Manchow Soup,800
8246,51617,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,51620,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [50]:
# Drop the old index column created during index reset
# Keeps the DataFrame clean without unnecessary columns
data.drop(columns="index", inplace=True)

In [51]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 /5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [52]:
data["Rate"]

0        4.1/5
1        4.1/5
2        3.8/5
3        3.7/5
4        3.8/5
         ...
8245    2.5 /5
8246    3.6 /5
8247    3.8 /5
8248    4.2 /5
8249    2.5 /5
Name: Rate, Length: 8250, dtype: object

In [53]:
# Remove extra spaces from the values in the 'Rate' column
# Updates the column to ensure consistent formatting for analysis
data["Rate"] = data["Rate"].str.replace(" ", "")

In [54]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5/5,Manchow Soup,800
8246,Breakfast House,No,No,3.6/5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8/5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2/5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5/5,"Biryani, Andhra Meal",800

In [55]:
# Replace the '/' character with descriptive text in the 'Rate' column
# Improves readability and standardizes the rating format
data["Rate"] = data["Rate"].str.replace("/", " out of ")

In [56]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7 out of 5,Masala Dosa,300
4,Grand Village,No,No,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 out of 5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 out of 5,"Biryani, Andhra Meal",800

# Checking for some more transformations

In [57]:
# Convert the 'Online_order' column from categorical values to binary format
# Assigns 1 if online ordering is available ("Yes"), otherwise assigns 0
# This makes the column suitable for numerical analysis
data["Online_order"] = data["Online_order"].apply(lambda x: 1 if x == "Yes" else 0)

In [58]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7 out of 5,Masala Dosa,300
4,Grand Village,0,No,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,No,2.5 out of 5,Manchow Soup,800
8246,Breakfast House,0,No,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,No,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,No,2.5 out of 5,"Biryani, Andhra Meal",800

In [59]:
# Save the cleaned DataFrame to a CSV file
# This exports the final, processed dataset for further analysis or reuse
data.to_csv("Cleaned_zomato.csv", index=False)

In [60]:
# Save the cleaned DataFrame to a CSV file
# This exports the final, processed dataset for further analysis or reuse
data.to_csv("Cleaned_zomato.csv", index=False)

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7 out of 5,Masala Dosa,300
4,Grand Village,0,No,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,No,2.5 out of 5,Manchow Soup,800
8246,Breakfast House,0,No,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,No,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,No,2.5 out of 5,"Biryani, Andhra Meal",800

In [ ]:
# Save the cleaned DataFrame to an Excel file
# index=False ensures the DataFrame index is not included as a separate column
data.to_excel("Cleaned_excel_zomato.xlsx", index=False)